Add minimum coverage

diff --git a/.github/workflows/backend.yaml b/.github/workflows/backend.yaml
--- a/.github/workflows/backend.yaml
+++ b/.github/workflows/backend.yaml
@@ -54,7 +54,16 @@ jobs:
         run: go mod download
 
       - name: Run Tests
-        run: go test -json ./... > testresults.json
+        run: go test -coverprofile=coverage.out -json ./... > testresults.json
+
+      - name: Enforce Min Coverage
+        run: |
+          COVERAGE=$(go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+')
+          echo "Current Coverage: $COVERAGE%"
+          if (( $(echo "$COVERAGE < 80.0" | bc -l) )); then
+            echo "Error: Coverage is below 80%! Current coverage is $COVERAGE%."
+            exit 1
+          fi
 
       - name: Upload Test Report
         uses: dorny/test-reporter@v2
